### ISSUE TITLE
Error messages in integration tests despite PASS

### ISSUE THREAD

**Issue by hyateh** [netsys-lab/scion-rains#19] opened 2021-12-10 16:33 UTC
The log from the integration tests report some error messages, e.g.,

> t=2021-11-03T10:23:11+0000 lvl=eror msg="Error sending message to server" sever=127.0.0.1:5024 err="error receiving message: failed to unmarshal CBOR: failed to read tag: read tcp 127.0.0.1:42650->127.0.0.1:5024: i/o timeout" caller=publisher.go:453

> t=2021-11-03T10:23:13+0000 lvl=eror msg="error while receiving response" err="failed to unmarshal CBOR: failed to read tag: EOF" caller=resolver.go:435

Similar messages are found while running test cases manually.

It would be good to investigate the causes and the severity of these errors.

**Comment by benthor** [comment] 2022-01-24 12:56
Duplicate of #20

**Closed as completed by benthor** 2022-01-24 12:56 UTC
